import Head from 'next/head'
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styled from "@emotion/styled";

const Layout = styled.div`
    width: 100vw;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    `;

const Main = styled.main`
  width: 100%;
  height:300vh;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>


        <Header />
        <Main />
        <Footer />
      </Layout>
    </>
  )
}
